name: cil21_tigre_astra
channels:
  - anaconda
  - ccpi
  - astra-toolbox/label/dev
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - anyio=2.2.0=py38h578d9bd_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - astra-toolbox=1.9.9.dev4=py38hb48bd9c_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py38h497a2fe_1001
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - ccpi-regulariser=20.09=np118py38_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - cftime=1.4.1=py38h5c078b8_0
  - chardet=4.0.0=py38h578d9bd_1
  - charls=2.2.0=h9c3ff4c_0
  - cil=21.0.0=np118py38_0
  - cil-astra=20.11.2=np118py38_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=9.2.148=h80a95b2_8
  - curl=7.76.1=h979ede3_1
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h48d8840_2
  - decorator=5.0.7=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - dxchange=0.1.6=pyhd3deb0d_0
  - dxfile=0.5=py_1
  - edffile=5.0.0=pyh24bf2e0_1000
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.1=h9c3ff4c_0
  - glib-tools=2.68.1=h9c3ff4c_0
  - gst-plugins-base=1.18.4=h29181c9_0
  - gstreamer=1.18.4=h76c114f_0
  - h5py=3.2.1=nompi_py38h9915d05_100
  - hdf4=4.2.13=h10796ff_1005
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.3.31=py38h1455ab2_0
  - importlib-metadata=4.0.1=py38h578d9bd_0
  - ipykernel=5.5.3=py38hd0cf306_0
  - ipympl=0.7.0=pyhd3eb1b0_0
  - ipython=7.22.0=py38hd0cf306_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38_7
  - jupyter-packaging=0.9.2=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyter_server=1.6.4=py38h578d9bd_0
  - jupyterlab=3.0.14=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.4.0=pyhd8ed1ab_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.4=h9c3ff4c_1
  - libastra=1.9.9.dev4=cuda_9.2_0
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang=11.1.0=default_ha53f305_0
  - libcurl=7.76.1=hc4aaa36_1
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.1=h3e27bee_0
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.0=nompi_hfa85936_101
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.1=hfd2b0eb_2
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.2.0=hdc55705_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h72842e0_4
  - libzip=1.7.3=h4de3113_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py38h497a2fe_3
  - matplotlib=3.4.1=py38h578d9bd_0
  - matplotlib-base=3.4.1=py38hcc49a3a_0
  - mistune=0.8.4=py38h497a2fe_1003
  - mysql-common=8.0.23=ha770c72_1
  - mysql-libs=8.0.23=h935591d_1
  - nb_conda_kernels=2.3.1=py38h578d9bd_0
  - nbclassic=0.2.7=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - netcdf4=1.5.6=nompi_py38h5e9db54_103
  - nodejs=14.8.0=hda19d22_0
  - notebook=6.3.0=pyha770c72_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.64=hb5efdd6_0
  - numpy=1.18.1=py38h8854b6b_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py38h1abd341_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38ha0e1e83_1
  - pip=21.0.1=pyhd8ed1ab_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-wget=3.2=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h5c078b8_3
  - pyzmq=22.0.3=py38h2035c66_1
  - qt=5.12.9=hda022c4_4
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - scipy=1.5.3=py38hb2138dd_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - sniffio=1.2.0=py38h578d9bd_1
  - spefile=1.6.1=pyhd3deb0d_0
  - sqlite=3.35.4=h74cdb3f_0
  - terminado=0.9.4=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - tifffile=2021.4.8=pyhd8ed1ab_0
  - tigre=2.1=np118py38_0
  - tk=8.6.10=h21135ba_1
  - tomlkit=0.7.0=py38h578d9bd_3
  - tomophantom=1.4.9=np118py38_0
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wget=1.20.1=h20c2e04_0
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zfp=0.5.5=h9c3ff4c_5
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - hurry-filesize==0.9
    - ipywidgets==7.6.3
    - jupyterlab-widgets==1.0.0
    - nbstripout==0.4.0
    - python3-wget==0.0.2b1
prefix: /home/vaggelis/miniconda3/envs/cil21_tigre_astra

