name: cil_binder
channels:
  - astra-toolbox/label/dev
  - intel
  - oxfordcontrol
  - ccpi
  - conda-forge
  - cvxgrp
  - astra-toolbox
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - astra-toolbox=1.9.9.dev7=py39h4319877_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - ccpi-regulariser=21.0.0=np120py39_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cfitsio=4.0.0=h9a35b8e_0
  - cftime=1.5.1.1=py39hce5d2b2_1
  - charls=2.2.0=h9c3ff4c_0
  - cil=21.3.0=np120py39_0
  - cil-astra=21.3.0=np120py39_0
  - cil-data=21.3.0=0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cudatoolkit=10.2.89=h8f6ccaa_9
  - curl=7.80.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - dxchange=0.1.7=pyhd8ed1ab_0
  - dxfile=0.5=py_1
  - edffile=5.0.0=pyh24bf2e0_1000
  - expat=2.4.1=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.28.3=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.70.2=h780b84a_0
  - glib-tools=2.70.2=h780b84a_0
  - gst-plugins-base=1.18.5=hf529b03_2
  - gstreamer=1.18.5=h9f60fe5_2
  - h5py=3.6.0=nompi_py39h7e08c79_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_103
  - icu=68.2=h9c3ff4c_0
  - imagecodecs=2021.11.20=py39h571908b_1
  - ipp=2021.4.0=intel_459
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libastra=1.9.9.dev7=cuda_10.2_0
  - libblas=3.9.0=12_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.80.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.2=h174f98d_0
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.5=hd57d9b9_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.0=py39hf3d152e_0
  - matplotlib-base=3.5.0=py39h2fa2bec_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.27=ha770c72_2
  - mysql-libs=8.0.27=hfa10184_2
  - ncurses=6.2=h58526e2_4
  - netcdf4=1.5.8=nompi_py39h64b754b_101
  - nspr=4.32=h9c3ff4c_1
  - nss=3.73=hb5efdd6_0
  - numpy=1.20.3=py39hdbf815f_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py39hde0f152_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.4.0=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.2.0=py39hce5d2b2_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - scipy=1.7.3=py39hee8e79c_0
  - setuptools=59.4.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - spefile=1.6.1=pyhd3deb0d_0
  - sqlite=3.37.0=h9cd32fc_0
  - tifffile=2021.11.2=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tomophantom=1.4.10=np120py39_0
  - tornado=6.1=py39h3811e60_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zfp=0.5.5=h9c3ff4c_8
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
prefix: /opt/anaconda3/envs/cil_binder
